### PR TITLE
fixing description for compress

### LINKED ISSUE #1947: [BUG] Crate documentation for compress on ApiClient is incorrect
## Bug Report
The crate doc for [`compress`](https://docs.rs/risc0-zkvm/latest/risc0_zkvm/struct.ApiClient.html#method.compress) on the ApiClient is incorrect -- it's currently a copypasta error from `identity_p254`. 
[This version](https://docs.rs/risc0-zkvm/latest/risc0_zkvm/trait.Prover.html#tymethod.compress) is more accurate.

## Steps to Reproduce
1. Go [here](https://docs.rs/risc0-zkvm/latest/risc0_zkvm/struct.ApiClient.html#method.compress)

## Expected behavior
See [this version](https://docs.rs/risc0-zkvm/latest/risc0_zkvm/trait.Prover.html#tymethod.compress) which is more accurate

### PR DESCRIPTION
**Pull request by pdg744**
fixes #1947

### CODE REVIEW

**Review by SchmErik — APPROVED** [review]

File: risc0/zkvm/src/host/api/client.rs [hunk 1]
```diff
@@ -349,11 +349,30 @@ impl Client {
...
     }
 
-    /// Prove the verification of a recursion receipt using the Poseidon254 hash function for FRI.
+    /// Compress a [Receipt], proving the same computation using a smaller representation.
     ///
-    /// The identity_p254 program is used as the last step in the prover pipeline before running the
-    /// Groth16 prover. In Groth16 over BN254, it is much more efficient to verify a STARK that was
-    /// produced with Poseidon over the BN254 base field compared to using Poseidon over BabyBear.
+    /// Proving will, by default, produce a [CompositeReceipt](crate::CompositeReceipt), which
+    /// may contain an arbitrary number of receipts assembled into continuations and compositions.
```
Comment (flaub) [inline risc0/zkvm/src/host/api/client.rs:355]: nit: replace 'continuations' with 'segments', and maybe 'compositions' with 'assumptions'.
