### PR TITLE
Override gcc version

### LINKED ISSUE #2575: CUDA high gcc version incompatibility
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Discord first?

- [X] This is not a support question.

### Description of bug

On some systems like `Arch Linux` that have high GCC versions such as 13 and upwards are incompatible with CUDA. Therefore we need a way to override the compiler that nvcc uses for compiling the CUDA kernels.

### Steps to reproduce

Try to compile the CUDA feature using a gcc version of 14.2.1. Will result in:
```
  --- stderr


  error occurred: Command LC_ALL="C" "nvcc" "-ccbin=c++" "-Xcompiler" "-O0" "-Xcompiler" "-ffunction-sections" "-Xcompiler" "-fdata-sections" "-Xcompiler" "-fPIC" "-m64" "-I" "/home/starkbamse/.cargo/git/checkouts/risc0-7d6ab9951628e5b1/71ecab3/risc0/sys/cxx" "-I" "/home/starkbamse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sppark-0.1.10/sppark" "-Xcompiler" "-Wall" "-Xcompiler" "-Wextra" "-DFEATURE_BABY_BEAR" "-arch=native" "-diag-suppress=177" "-diag-suppress=2922" "-Xcudafe" "--display_error_number" "-Xcompiler" "-Wno-missing-braces,-Wno-unused-function" "-o" "/home/starkbamse/GitHub/sparkle/target/debug/build/risc0-sys-b135acaf3de15a89/out/01ed5306a404dc2c-ntt.o" "-c" "--device-c" "kernels/zkp/cuda/supra/ntt.cu" with args nvcc did not execute successfully (status code exit status: 2).


warning: build failed, waiting for other jobs to finish...
```

### PR DESCRIPTION
**Pull request by saefstroem**
Closes #2575 
Closes ZKVM-736

This allows the user to specify `NVCC_CCBIN` and override the default gcc compiler that is used by the nvcc compiler as the cc build tool does not adhere to if this variable is simply set from the linux environment.

### CODE REVIEW

**Comment by saefstroem** [comment]
@flaub

**Comment by flaub** [comment]
Related: #2695

**Comment by saefstroem** [comment]
> Possibly duplicate: #2695 

That is the duplicate. This PR is 2mo old :)

**Comment by flaub** [comment]
Are they both trying to do the same thing?

**Comment by saefstroem** [comment]
> Are they both trying to do the same thing?

Yes but this PR allows the specification of the native Nvidia env variables instead of creating custom logic. This is a one-line fix.

**Review by flaub — APPROVED** [review]

File: risc0/build_kernel/src/lib.rs [hunk 1]
```diff
@@ -197,6 +198,7 @@ impl KernelBuild {
             .cuda(true)
             .cudart(&cudart)
             .debug(false)
+            .ccbin(false)
```
Comment (flaub) [inline risc0/build_kernel/src/lib.rs:201]: This seems to break in our CI environment. Is there a way we can make this conditional? Perhaps only if `NVCC_CCBIN` is defined?

**Review by flaub — CHANGES_REQUESTED** [review]

File: risc0/build_kernel/src/lib.rs (hunk 1 above)
Comment (saefstroem) [reply risc0/build_kernel/src/lib.rs:201]: This is a good idea. I'll update it to only disable if that env var is defined.

**Comment by saefstroem** [comment]
@flaub

File: risc0/build_kernel/src/lib.rs [hunk 2]
```diff
@@ -193,10 +194,13 @@ impl KernelBuild {
...
+        let build = build.cuda(true).cudart(&cudart).debug(false);
+
+        if env::var("NVCC_CCBIN").is_ok() {
+            build.ccbin(false);
+        }
+
         build
-            .cuda(true)
-            .cudart(&cudart)
-            .debug(false)
```
Comment (flaub) [inline risc0/build_kernel/src/lib.rs:199]: How about this?

```
build
    .cuda(true)
    .cudart(&cudart)
    .debug(false)
    .ccbin(!env::var("NVCC_CCBIN").is_ok())
```

**Comment by saefstroem** [comment]
@flaub Good suggestion, simplified even further :)

**Comment by flaub** [comment]
Almost there, can you bump the first line so it reads:
```
// Copyright 2025 RISC Zero, Inc.
```

**Comment by saefstroem** [comment]
> Almost there, can you bump the first line so it reads:
> 
> ```
> // Copyright 2025 RISC Zero, Inc.
> ```

done :)

**Review by flaub — APPROVED** [review]
