### PR TITLE
Speed up risc0-build

### LINKED ISSUE #1985: [BUG] risc0-build panics when RISC0_SKIP_BUILD=1 is set and a guest is present in the workspace
## Bug Report

When building a workspace or running cargo clippy with RISC0_SKIP_BUILD=1 set it triggers a unwrap() to panic in risc0-build because guest_methods() assumes the existance of the guest elfs on disk. 

```
  thread 'main' panicked at /home/user/src/risc0/risc0/build/src/lib.rs:220:14:
  called `Result::unwrap()` on an `Err` value: No such file or directory (os error 2)
```

## Steps to Reproduce
1. in `risc0` repo
2. `cargo clean`
3. `RISC0_SKIP_BUILD=1 cargo clippy`

## Expected behavior

When RISC0_SKIP_BUILD is set the guest build should not panic

### PR DESCRIPTION
**Pull request by flaub**
Two major issues:
* build scripts are built with the dev profile by default, so compute_image_id is 20x slower than a release build. So call out to `r0vm` to compute the image_id.
* `include_bytes!()` is much faster at scale than embedding the string form of the ELF into methods.rs
* Fixes #1985

This helps especially for null builds

### CODE REVIEW

**Review by nuke-web3 — APPROVED** [review]
Didn't test locally, but LGTM with a light review of the diff - love to hear this will make (some) build workflows faster!

File: risc0/build/src/lib.rs [hunk 1]
```diff
@@ -490,6 +512,30 @@ fn build_staticlib(guest_pkg: &str, features: &[&str]) -> String {
     }
 }
 
+// HACK: Attempt to bypass the parent cargo output capture and
+// send directly to the tty, if available.  This way we get
+// progress messages from the inner cargo so the user doesn't
+// think it's just hanging.
+fn tty_println(msg: &str) {
```
Comment (nuke-web3) [inline risc0/build/src/lib.rs:519]: Love this, although related to https://github.com/risc0/risc0/issues/1685

Aside: I think we need better loading /progress information, as spinners don't give an idea if you are stuck or not in many cases, like `rzup` and `cargo risczero install`

Comment (flaub) [reply risc0/build/src/lib.rs:519]: We don't have that option since we're running inside the context of a cargo build process.
